<?php
/**
* 
*/

// Display TAB navigator.
?>
<div id="cjt-grouper-tab-navigator">
	<ul class="navigator">
<?php foreach ($this->getParams() as $groupKey => $group) : ?>	
		<li><a href="#<?php echo $groupKey; ?>"><?php echo $group['name'] ?></a></li>
<?php endforeach; ?>
	</ul>
<?php // Display TABS ?>
<?php foreach ($this->getParams() as $group) : ?>
	<div id="<?php echo $groupKey; ?>">
		<ul class="params-list">
<?php foreach ($group['params'] as $param) : ?> 
<li><?php echo $param; ?></li>
<?php endforeach; ?>
		</ul>
	</div>
<?php endforeach; ?>
</div>
<script type="text/javascript">
	// Apply TABs Plugin!
	jQuery(function($) {
		$('#cjt-grouper-tab-navigator').tabs();
		// Force form size.
		var size = {'width' : '670px', 'height' : '600px'};
		parent.jQuery('#TB_window').css(size);
		size.height -= 10;
		parent.jQuery('#TB_iframeContent').css(size);
		// Set tab size.
		$('#cjt-grouper-tab-navigator').css({height: '527px'});
	});
	
	
</script>